rfd_app/RSSFeed/urls.py
from django.conf.urls import url   
from . import views
app_name = 'RSSFeed'

urlpatterns = [
    url(r'^add_rss_feed/$', views.addRssFeed, name='add_rss_feed'),
    url(r'^remove_rss/$', views.RemoveRss, name='remove_rss'),
    url(r'^feed/$', views.feed, name='feed'),
    url('',views.feed, name='feed')
    



]

rfd_app/Weather/urls.py
from django.conf.urls import url   
from . import views
app_name = 'Weather'

urlpatterns = [
    url(r'^add_weather/$', views.addWeather, name='add_weather'),
    url(r'^weather/$', views.WeatherAll, name='weather'),
    url('',views.WeatherAll, name='weather')



]

rfd_app/accounts/urls.py
from django.conf.urls import url   
from . import views
app_name = 'Accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.loginV, name='login'),
    url(r'^logout/$',views.logoutV, name='logout'),
    url(r'^change_password/$',views.changePassword, name='change_password'),
    url(r'^edit_profile/$',views.editProfile, name='edit_profile'),
    url(r'^profile/$',views.profile, name='profile'),
    url(r'^settings/$',views.settings, name='settings'),
    url('',views.profile, name='profile')

    



]

rfd_app/rfd_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rfd_web.urls')),
    path('accounts/',include('accounts.urls')),
    path('Weather/',include('Weather.urls')),
    path('RSSFeed/',include('RSSFeed.urls')),
 ]

rfd_app/rfd_web/urls.py
from django.urls import path
from . import views
app_name = 'rfd_web'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_device', views.addDevice, name='add_device'),
    path('device_detail/<int:device_id>/', views.deviceDetail, name='device_detail'),
    path('device_action/<int:device_id>/<path:action>', views.deviceAction, name='device_detail'),
    path('device_feed', views.deviceFeed, name='device_feed'),
    path('remove_device/',views.removeDevice, name='remove_device'),

]

rfd_app/rfd_web/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class DeviceType(models.Model):
    name = models.CharField(max_length = 50)
    def __str__(self):
        return self.name

class SmartDevice(models.Model):
    device_type = models.ForeignKey(DeviceType, on_delete=models.CASCADE)
    name = models.CharField(max_length = 50)
    ip = models.GenericIPAddressField()
    def __str__(self):
        return self.name

rfd_app/rfd_web/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import SmartDevice, DeviceType
from RSSFeed.models import RssFeed
from Weather.models import Weather, Unit
from accounts.models import Setting
import urllib.request
import feedparser
import json
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        setting_list = Setting.objects.filter(user=User.objects.get(username = request.user.get_username()))
        for setting in setting_list:
            if setting.units ==  Unit.objects.get(unit='°C + km/h'):
                unit = 'ca'
            elif setting.units == Unit.objects.get(unit='°F + mp/h'):
                unit = 'us'
            else:
                unit='ca'
        device_list = SmartDevice.objects.all()
        pocasi_list = Weather.objects.filter(user=User.objects.get(username = request.user.get_username()))
        feeds = []
        UrlTables = RssFeed.objects.filter(user=User.objects.get(username = request.user.get_username()))
        for Table in UrlTables:
            feeds.append(feedparser.parse(Table.url))
        context = {'device_list': device_list, 'pocasi_list':pocasi_list,'feeds':feeds, 'unit':unit}
        return render(request, 'dashboard.html', context)
    else:
        device_list = SmartDevice.objects.all()
        context = {'device_list': device_list}
        return render(request, 'dashboard_unlogged.html', context)

def removeDevice(request):
    if request.method == 'POST':
        SmartDevice.objects.filter(id=request.POST['id']).delete()
        return redirect('Accounts:settings')
    device_list = SmartDevice.objects.all()
    context = {'device_list':device_list}
    return render(request, 'remove_device.html', context)

@login_required(login_url='/accounts/login/')
def addDevice(request):
    if request.method == 'POST':
        data = SmartDevice(device_type=DeviceType.objects.get(id=request.POST['device_type']),name=request.POST['name'],ip=request.POST['ip'])
        data.save()
        return HttpResponseRedirect('/')
    device_list = DeviceType.objects.all()
    context = {'device_list': device_list}
    return render(request, 'add_device.html', context)


def deviceDetail(request, device_id):
    device = get_object_or_404(SmartDevice, pk=device_id)
    return render(request, 'device_detail.html', {'device': device})

def deviceAction(request, device_id, action):
    device = get_object_or_404(SmartDevice, pk=device_id)
    url = "http://" + device.ip + "/" + action
    urllib.request.urlopen(url)
    return redirect('rfd_web:device_detail', device_id = device.id)
    #return render(request, 'device_detail.html', {'device': device})

def deviceFeed(request):
    device_list = SmartDevice.objects.all()
    context = {'device_list': device_list}
    return render(request, 'device_feed.html', context)

rfd_app/rfd_web/templates/add_device.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='obalCenter'>
    <form id='form' method='POST' class='settingBUT' name='form' action="#">
        Type: <br>
        <select class='settingBUT' name="device_type">
            {% for device in device_list %}
            <option  value="{{ device.id }}">{{ device.name }}</option>
            {% endfor %}
        </select>
        <br>
        {% csrf_token %}
        Name: <br>
        <input class='settingBUT' type="text" name="name" id="name">
        <br>
        IP: <br>
        <input class='settingBUT' type='text' name='ip' id='ip'>
        <br>
    </form>

<button type="submit" class='settingBUT btn btn-success'  onclick='ValidateIPaddress()'>Add</button>
<div id='error'> </div>
</div>
    <script>

document.getElementById('home').classList.remove("active");
document.getElementById('devices').classList.add("active");

function ValidateIPaddress()
 {
 ipAdresa = document.getElementById("ip");
 var ipformat = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
 if(ipAdresa.value.match(ipformat) && document.getElementById('name').value != "" )
 {
document.getElementById("form").submit();
 }

else if(ipAdresa.value.match(ipformat))
 {
document.getElementById("error").innerHTML= 'You have not enetered a name!';

 }
 else{
document.getElementById("error").innerHTML= 'You have entered an invalid IP address!';

 document.getElementById("ip").value='';
 }
 }
    </script>

{% endblock %}

rfd_app/rfd_web/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'rfd_web/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'rfd_web/favicon.ico' %}" type="image/x-icon">
    <title>RFD-APP</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse">
        <span class='oddelovac'> </span>
        <ul class="nav nav-tabs">
  <li class="nav-item">
   <a class="nav-link active" id='home' href={% url 'rfd_web:index' %}>Home</a>
  </li>
  <li class="nav-item">
   <a class="nav-link" id='news' href={% url 'RSSFeed:feed' %}>News</a>
  </li>
  <li class="nav-item">
   <a class="nav-link" id='weather' href={% url 'Weather:weather' %}>Weather</a>
  </li>
  
  <li class="nav-item">
   <a class="nav-link " id='devices' href={% url 'rfd_web:device_feed' %}>My Devices</a>
  </li>
</ul>
<ul class='nav nav-tabs navbar-right '>
<div class="nav-item dropdown btn-group">
   {% if user.is_authenticated %}
  <button class="btn btn-secondary dropdown-toggle" title='{{user.first_name}} {{user.last_name}}' type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {{user.username}}
  </button>
  <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href={% url 'Accounts:profile' %}>Profile</a>
    <a class="dropdown-item" href={% url 'Accounts:settings' %}>Settings</a>
        <div class="dropdown-divider"></div>
    <form class="dropdown-item" action="{% url 'Accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button  class="btn btn-danger"  type="submit">
                        Logout
                    </button>
                </form>
                  </div>
                  
 {% else %}
 <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-display="static" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Login/Register
  </button>
 <div class="dropdown-menu dropdown-menu-right" >




            <form class="dropdown-item" action="{% url 'Accounts:login' %}" >
                {% csrf_token %}
                <button class="btn" type="submit">
                    Login
                </button>
            </form>
<div class="dropdown-divider"></div>
            <form class="dropdown-item" action="{% url 'Accounts:signup' %}" >
                {% csrf_token %}
                <button class="btn" type="submit">
                    Register
                </button>
            </form>

</div>
{% endif %}
</div>

</ul>

</nav>
</header>
    {% block content %}

    {% endblock %}

        
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
</body>

</html>

rfd_app/rfd_web/templates/dashboard.html
{% extends 'base_layout.html' %}

{% block content %}

<div class='Blok left_side Device'> 
<h2 class='Center'>Devices</h2> 
<ul>
    {% for device in device_list %}
    <li class='LIST'>
        <a href="{% url 'rfd_web:device_detail' device.id %}">{{ device.name }}</a>
    </li>
    {% endfor %}
</ul>
<div class='Center'>
    <a href ={% url 'rfd_web:add_device' %}> Add Device!</a>
    </div>
</div>

<div  class='Blok Feed right_side '>
<h2 class='Center'> NewsFeed </h2>
<ul>
{% for feed in feeds %}
{% for entry in feed.entries %}
{% if forloop.counter < 2 %}
    <li><a href="{{entry.link}}">{{entry.title}}</a>
    {{entry.source}}
     </li>
   {% endif %}
{% endfor %}

{% endfor %}
</ul>
<div class='Center'>
    <a href ={% url 'RSSFeed:add_rss_feed' %}> Add RSS Feed!</a>
    </div>
    </div>








    {% if pocasi_list %}
    
<div class='Weather'> 
    <h2 > Weather </h2>
    {% for pocasi in pocasi_list %}
   <script type='text/javascript' src='https://darksky.net/widget/small/{{pocasi.lat}},{{pocasi.lon}}/{{unit}}12/en.js?width=100%&height=200&title={{pocasi.location}}&textColor=333333&bgColor=ff2424&transparency=true&skyColor=undefined&fontFamily=Verdana&customFont=&units=uk'></script>
   <div >
    <a href ={% url 'Weather:add_weather' %}> Change the location</a>
    </div>
    </div>
{% endfor %}
    {% else %}
        <div>
    <a href ={% url 'Weather:add_weather' %}> Add Location to Display weather!</a>
    </div>
    {% endif %}
    
  {% endblock %}

rfd_app/rfd_web/templates/dashboard_unlogged.html
{% extends 'base_layout.html' %}

{% block content %}

<h2>Devices</h2>

<ul>
    {% for device in device_list %}
    <li style='
  list-style-type: none;'>
        <a href="{% url 'rfd_web:device_detail' device.id %}">{{ device.name }}</a>
    </li>
    {% endfor %}
</ul>


  {% endblock %}

rfd_app/rfd_web/templates/device_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<div style='padding:20px'>
<h1>{{ device.name }}</h1>
<form action="/device_action/{{device.id}}/on" method="post">
    {% csrf_token %}
    <button class='btn btn-success' type="submit">On</button>
</form><form action="/device_action/{{device.id}}/off" method="post">
    {% csrf_token %}
    <button class='btn btn-danger' type="submit">Off</button>
</form>
</div>
<script>
document.getElementById('home').classList.remove("active");
document.getElementById('devices').classList.add("active");
</script>
{% endblock %}

rfd_app/rfd_web/templates/device_feed.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='obalCenter'>
<h2> Devices </h2>
<ul>
    {% for device in device_list %}
    <li 
class='LIST'>
    
       <form  action="/device_action/{{device.id}}/on" method="post">
    {% csrf_token %}
    <button class='btn settingBUT btn-success' type="submit">On</button>
</form><form  action="/device_action/{{device.id}}/off" method="post">
    {% csrf_token %}
    <button class='btn settingBUT btn-danger' type="submit">Off</button>
</form>
       {{ device.name }} - {{device.device_type}}


</span>
    </li>

    {% endfor %}
</ul>

</div>
<script>
document.getElementById('home').classList.remove("active");
document.getElementById('devices').classList.add("active");
</script>
  {% endblock %}

rfd_app/rfd_web/templates/remove_device.html
{% extends 'base_layout.html' %}
{% block content %}
<div class='obalCenter'> 
{% for Device in device_list %}
<form action='#' method='POST' class='settingBUT'>
{{Device.name}} <input class="btn left_side btn-danger" type='submit' value='Odebrat'/>
<input type='hidden' value='{{Device.id}}' name='id'/>
{% csrf_token %}
</form>
<br>
{% endfor %}
</div>

<script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}