rfd_app/RSSFeed/urls.py
from django.conf.urls import url   
from . import views
app_name = 'RSSFeed'

urlpatterns = [
    url(r'^add_rss_feed/$', views.addRssFeed, name='add_rss_feed'),
    url(r'^remove_rss/$', views.RemoveRss, name='remove_rss'),
    url(r'^feed/$', views.feed, name='feed'),
    url('',views.feed, name='feed')
    



]

rfd_app/accounts/urls.py
from django.conf.urls import url   
from . import views
app_name = 'Accounts'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.loginV, name='login'),
    url(r'^logout/$',views.logoutV, name='logout'),
    url(r'^change_password/$',views.changePassword, name='change_password'),
    url(r'^edit_profile/$',views.editProfile, name='edit_profile'),
    url(r'^profile/$',views.profile, name='profile'),
    url(r'^settings/$',views.settings, name='settings'),
    url('',views.profile, name='profile')

    



]

rfd_app/rfd_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rfd_web.urls')),
    path('accounts/',include('accounts.urls')),
    path('Weather/',include('Weather.urls')),
    path('RSSFeed/',include('RSSFeed.urls')),
 ]

rfd_app/rfd_web/urls.py
from django.urls import path
from . import views
app_name = 'rfd_web'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_device', views.addDevice, name='add_device'),
    path('device_detail/<int:device_id>/', views.deviceDetail, name='device_detail'),
    path('device_action/<int:device_id>/<path:action>', views.deviceAction, name='device_detail'),
    path('device_feed', views.deviceFeed, name='device_feed'),
    path('remove_device/',views.removeDevice, name='remove_device'),

]

rfd_app/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from Weather.models import Unit

# Create your models here.
class Setting(models.Model):
    number_of_posts = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    units = models.ForeignKey(Unit, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

rfd_app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, login, logout
from django.contrib.auth.models import User
from .models import Setting
from Weather.models import Unit
from accounts.form import RegistForm, EditProfileForm
# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = RegistForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            data = Setting(number_of_posts=5,user = User.objects.get(username = request.user.get_username()), units= Unit.objects.get(unit='°C + km/h'))
            data.save()
            return redirect('rfd_web:index')
    else:
        form = RegistForm()
    return render(request,'signup.html', {'form': form})

def loginV(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('rfd_web:index')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logoutV(request):
    if request.method == 'POST':
        logout(request)
        return redirect('Accounts:login')

@login_required(login_url='/accounts/login/')
def changePassword(request):
    if request.method =='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/')
    else:
        form = PasswordChangeForm(request.user)
    return render(request,'change_password.html', {'form':form})

@login_required(login_url='/accounts/login/')
def editProfile(request):
    if request.method == 'POST':
        form=EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('rfd_web:index')

    form = EditProfileForm(instance=request.user)
    context = {'form':form}
    return render(request, 'edit_profile.html', context)

@login_required(login_url='/accounts/login/')
def profile(request):
    return render(request, 'profile.html')

@login_required(login_url='/accounts/login/')
def settings(request):
    if request.method == 'POST':
        #Setting.objects.filter(user = User.objects.get(username = request.user.get_username())).delete()
        Setting_data = Setting.objects.get(user = User.objects.get(username = request.user.get_username()))
        #data = Setting(number_of_posts=request.POST['number_of_posts'],units=Unit.objects.get(unit=request.POST['units']),user=User.objects.get(username = request.user.get_username()))
        #data.save()
        #To přece nebudu kvůli editu mazat FailFish
        Setting_data.number_of_posts = request.POST['number_of_posts']
        Setting_data.units = Unit.objects.get(unit=request.POST['units'])
        Setting_data.save()
        return redirect('Accounts:settings')
    Settings = Setting.objects.filter(user=User.objects.get(username = request.user.get_username()))
    Units = Unit.objects.exclude(unit=Setting.objects.get(user=User.objects.get(username = request.user.get_username())).units)
    context = {'Settings':Settings, 'Units':Units}
    return render(request, 'settings.html', context)

rfd_app/accounts/templates/change_password.html
{% extends 'base_layout.html' %}
{% load widget_tweaks %}
{% block content %}

<div class='obalCenter'>
    <h1> Change your password!</h1>
    <form class='settingBUT' action="" method="POST">
           {% for field in form %}
      <p>
        {{ field.label_tag }}

      <br>
        {{ field|add_class:"settingBUT" }}
              </p>
    {% endfor %}

  
        {% csrf_token %}
        <input class='btn settingBUT btn-success' type="submit" value="Save">
    </form>
    <div>
    <script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}

rfd_app/accounts/templates/edit_profile.html
{% extends 'base_layout.html' %}
{% load widget_tweaks %}
{% block content %}
<div class='obalCenter'>
<h1> Edit your profile!</h1>
    <form action="" class='settingBUT'method="POST">

         {% for field in form %}
      <p>
      
        {{ field.label_tag}}
      <br>
        {{ field |add_class:"settingBUT" }}

              </p>
    {% endfor %}

        {% csrf_token %}
        <input class="btn settingBUT btn-success " type="submit" value="Save">
    </form>
    </div>
    <script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}

rfd_app/accounts/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='obalCenter'>
    <h1> Log in </h1>
    <form action="{% url 'Accounts:login' %}" method="POST">
          {% for field in form %}
         
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
        {% if request.GET.next %}
            <input type="hidden" name='next' value="{{request.GET.next}}">
        {% endif %}
        {% csrf_token %}
        <input class='settingBUT btn btn-success' type="submit" value="Log in">
    </form>
    
    <div><p>New to RFD? <a href={% url 'Accounts:signup' %}>Sign up now</a></p> </div></div>
    <script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}

rfd_app/accounts/templates/profile.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='obalCenter'>
<h1>This is your account information, {{user.username}}.</h1>
 <br>

   <div>
   <h3> Basic information </h3>
    <p> First name: {{user.first_name}}</p>
    <p> Last name: {{user.last_name}}</p>
    <p> Email name: {{user.email}}</p>
    <a href={% url 'Accounts:edit_profile' %}> <button class="btn settingBUT btn-info"  type="submit">Change </button> </a>
   </div>

    <div>
    <h3> Password </h3>
    <a href={% url 'Accounts:change_password' %}> <button class="btn settingBUT btn-info"  type="submit">Change </button> </a>
   </div>
</div>

   
    <script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}

rfd_app/accounts/templates/settings.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='obalCenter'>
<div>
<h3>Settings</h3>
<form action='' method='POST' class='settingBUT'>
{% for Setting in Settings %}

<p>
Number of posts in each RSS feed: 
<input id="number_of_posts" name='number_of_posts' type="number" min="0" value="{{Setting.number_of_posts}}">
   </p>
   <br>
  Units for Weather forecast:
   <select name='units' id='units'>
<option value='{{Setting.units}}'> {{Setting.units}} </option>
{% endfor %}
{% for Unit in Units %}
<option value='{{Unit.unit}}'> {{Unit.unit}} </option>
{% endfor %}
</select>
<br>
<input class="btn btn-success settingBUT" type='submit' value='Save'/>
{% csrf_token %}
</form>
</div>
    <div>
    <h3> Rss Feeds </h3>
    <a href={% url 'RSSFeed:remove_rss' %}> <button  class="btn settingBUT btn-danger"  type="submit">Remove Rss Feed </button> </a>
<br>
      <a href={% url 'RSSFeed:add_rss_feed' %}> <button class="settingBUT btn btn-info"  type="submit">Add Rss Feed </button> </a>
   </div>
    <div>
    <h3> Devices </h3>
    <a href={% url 'rfd_web:remove_device' %}> <button class="btn settingBUT btn-danger"  type="submit">Remove Device </button> </a>
<br>
   <a href={% url 'rfd_web:add_device' %}> <button class="btn btn-info settingBUT"  type="submit">Add Device </button> </a>
   </div>
   </div>



{% endblock %}

rfd_app/accounts/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<div class='obalCenter'>
    <h1> Signup </h1>
    <form action="{% url 'Accounts:signup' %}" method="POST">
         {% for field in form %}
         
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
        {% csrf_token %}
        <input class='settingBUT btn btn-success' type="submit" value="Sign Up">
    </form>
    <div><p>Already have an Account? <a href={% url 'Accounts:login' %}>Login now!</a></p> </div>

    </div>
<script>
document.getElementById('home').classList.remove("active");
</script>
{% endblock %}